# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  POSTGRES_CONNECTION_URL: postgresql://postgres:Ip5HbnyVrNpK8FQg6TT7@containers-us-west-85.railway.app:6519/railway

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    -   run: |
          touch .env
          echo POSTGRES_CONNECTION_URL="postgresql://postgres:Ip5HbnyVrNpK8FQg6TT7@containers-us-west-85.railway.app:6519/railway" >> .env
          cat .env
    - run: npm ci
    - run: npm start & npx-wait-on http://localhost:3000
    - run: npm test
